var data=JSON.parse(localStorage.getItem("product"));
console.log(data);
document.querySelector("#product-name").innerText=data.name;
let image=document.createElement("img");
image.setAttribute("src",data.image);
document.querySelector("#image").append(image);
document.querySelector("#details").innerText=data.details;
document.querySelector("#desc").innerText=data.description;
let price=document.createElement("h2");
price.innerText=data.price;
let pname=document.createElement("h3");
pname.innerText=data.name;
pname.style.color="grey";
let desc=document.createElement("h4");
desc.innerText=data.description;
desc.style.color="grey";
let more= document.createElement("div");
let loc=document.createElement("p");
loc.innerText=data.location;
loc.style.color="grey";
let day=document.createElement("p");
day.innerText=data.uploaded;
day.style.color="grey";
more.append(loc,day);
document.querySelector("#price").append(price,pname,desc,more);

let seller=document.createElement("h2");
seller.innerText="Seller Description";
let sname=document.createElement("h3");
sname.innerText=data.seller;
let sdesc=document.createElement("h4");
sdesc.innerText=data.description;
let chat=document.createElement("button");
chat.innerText="Chat with Seller";
document.querySelector("#seller").append(seller,sname,sdesc,chat);